title: spyduck007
description: >
  A blank Serial Programmer Jekyll theme ready for customization.
url: https://hsna674.github.io
baseurl: "/ctf"
markdown: kramdown
kramdown:
  input: GFM

author:
  name: "spyduck007 (Ansh)"
  email: ""

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "write-ups"
    values:
      layout: "post"
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]